name: Deploy Valar
on:
  push:
    branches: [feat/websocket]
jobs:
  deploy-valar:
    env:
      NODE_VER: 17.0.1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Corriendo el workflow ${{ github.workflow }} por un ${{ github.event_name }} en ${{ github.ref }}."
      - name: Get Valar Source Code
        uses: actions/checkout@v2
      - run: echo "El repo ${{ github.repository }} ha sido clonado en el runner."
      - name: Listar los archivos descargados del repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "Instalando la version ${{ env.NODE_VER }} de Node.js"
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          version: "${{ env.NODE_VER }}"
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install Dependencies with Yarn
        run: yarn
      - name: Create .env
        run: |
          touch .env
          echo "${{ secrets.DB_URL }}" >> .env
          echo "${{ secrets.JWT_SECRET }}" >> .env
          echo "${{ secrets.COOKIES_SECRET }}" >> .env
          echo "${{ secrets.SENDGRID_API_KEY }}" >> .env
          echo "NODE_ENV=production" >> .env
      - name: Build Project
        run: yarn build
      - name: Copy dist folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./dist/*"
          target: "/home/ubuntu/valar-backend/dist/"
      - name: Copy dist folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./package.json"
          target: "/home/ubuntu/valar-backend/"
      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/valar-backend/
            yarn
            cd dist
            echo ${{ secrets.PASSWORD }} | sudo -S pm2 restart index.js
