name: Deploy Valar
on:
  push:
    branches: [create-github-action]
jobs:
  deploy-valar:
    env:
      NODE_VER: 17.0.1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Corriendo el workflow ${{ github.workflow }} por un ${{ github.event_name }} en ${{ github.ref }}."
      - name: Get Valar Source Code
        uses: actions/checkout@v2
      - run: echo "El repo ${{ github.repository }} ha sido clonado en el runner."
      - name: Listar los archivos descargados del repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "Instalando la version ${{ env.NODE_VER }} de Node.js"
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          version: "${{ env.NODE_VER }}"
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install Dependencies with Yarn
        run: yarn
      - name: Create .env
        run: |
          touch .env
          echo "${{ secrets.DB_URL }}" >> .env
          echo "${{ secrets.JWT_SECRET }}" >> .env
          echo "${{ secrets.COOKIES_SECRET }}" >> .env
          echo "${{ secrets.SENDGRID_API_KEY }}" >> .env
      - name: Build Project
        run: yarn build
      # TODO: copiar solo ./dist al servidor
